version: "3.9"

services:
  config-sv:
    build: ./config-sv
    restart: always
    ports:
      - "8888:8888"
    environment:
      GIT_USER: ${GIT_USER}
      GIT_PASSWORD: ${GIT_PASSWORD}
    networks:
      - bazarmicroservicio
  eureka-sv:
    build: ./eureka-sv
    restart: always
    ports:
      - "8761:8761"
    depends_on:
      config-sv:
        condition: service_started
    networks:
      - bazarmicroservicio
  api-gateway:
    build: ./api-gateway
    restart: always
    ports:
      - "443:443"
    depends_on:
      config-sv:
        condition: service_started
      eureka-sv:
        condition: service_started
    networks:
      - bazarmicroservicio
  clientes-service:
    build: ./clientes-service
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      db-cliente-service:
        condition: service_started
      config-sv:
        condition: service_started
      eureka-sv:
        condition: service_started
      api-gateway:
        condition: service_started
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - bazarmicroservicio
  db-cliente-service:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: bazar-cliente-service
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-cliente-service-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_spanish_ci
    ports:
      - "3306:3306"
    networks:
      - bazarmicroservicio
networks:
  bazarmicroservicio:
volumes:
  db-cliente-service-data:

  
  