server:
  port: 443
eureka:
  client:
    service-url:
      defaultZone: http://eureka-sv:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    openfeign:
      client:
        config:
          authapi:
            url: http://api-gateway/auth
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: clientes-service
          uri: lb://CLIENTES-SERVICE
          predicates:
            - Path=/clientes/**
          filters:
            - AuthFilter
        - id: detalles-ventas-service
          uri: lb://DETALLES-VENTAS-SERVICE
          predicates:
            - Path=/detalles/**
          filters:
            - AuthFilter
        - id: productos-service
          uri: lb://PRODUCTOS-SERVICE
          predicates:
            - Path=/productos/**
          filters:
            - AuthFilter
        - id: ventas-service
          uri: lb://VENTAS-SERVICE
          predicates:
            - Path=/ventas/**
          filters:
            - AuthFilter
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - AuthFilter

public-paths:
  paths:
    -
      uri: "/auth/login"
      method: "POST"
    -
      uri: "/auth/validate"
      method: "POST"