server:
  port: 443
eureka:
  client:
    service-url:
      defaultZone: http://eureka-sv:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true