server:
  port: 443
eureka:
  client:
    service-url:
      defaultZone: http://eureka-sv:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
        - id: api-gateway
          uri: lb://APY-GATEWAY
          predicates:
            - Method=GET,POST,DELETE,PUT
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - AuthFilter
        - id: clientes-service
          uri: lb://CLIENTES-SERVICE
          predicates:
            - Path=/clientes/**
          filters:
            - AuthFilter
        - id: detalles-ventas-service
          uri: lb://DETALLES-VENTAS-SERVICE
          predicates:
            - Path=/detalles/**
          filters:
            - AuthFilter
        - id: productos-service
          uri: lb://PRODUCTOS-SERVICE
          predicates:
            - Path=/productos/**
          filters:
            - AuthFilter
        - id: ventas-service
          uri: lb://VENTAS-SERVICE
          predicates:
            - Path=/ventas/**
          filters:
            - AuthFilter

public-paths:
  paths:
    -
      uri: "/auth/login"
      method: "POST"
    -
      uri: "/auth/validate"
      method: "POST"