server:
  port: 9091
eureka:
  client:
    service-url:
      defaultZone: http://eureka-sv:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

admin-paths:
  paths:
    -
      uri: "/clientes/crear"
      method: "POST"
    -
      uri: "/clientes/actualizar/{1}.+"
      method: "PUT"
    -
      uri: "/auth/create"
      method: "POST"

jwt:
  secret: ${JWT_SECRET}