server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://eureka-sv:8761/eureka

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}