server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://eureka-sv:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  cloud:
    openfeign:
      client:
        config:
          detalleapi:
            url: http://api-gateway:443/detalles-ventas-service/detalles