server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://eureka-sv:8761/eureka
  instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

feign:
  detalleapi:
    url: http://api-gateway:443/detalles-ventas-service/detalles
  clienteapi:
    url: http://api-gateway:443/clientes-service/clientes