server:
  port: 8081

spring:
  application:
    name: config-sv

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Leandrogd9/GestorVentaParaBazarMicroservicio
          search-paths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}