server:
  port: 8888

spring:
  application:
    name: config-sv
  #profiles:
   # active: development

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Leandrogd9/GestorVentaParaBazarMicroservicio
          search-paths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
          default-label: master
          clone-on-start: true